### ISSUE TITLE
Is this repository a perfect replica of the MAnorm package, but in python? 

### ISSUE THREAD

**Issue by alexlenail** [semal/MAnormFast#3]
Is there a publication linked to this repository?

**Comment by semal** [comment]
Yes, you could see the detail from http://139.224.227.24:2013/. The MAnorm is a method for normalizing chip-seq signal between samples.

**Comment by alexlenail** [comment]
Would it be alright if I added this tool to [Galaxy](https://galaxyproject.org/)?
